In [1]:
import torch

In [2]:
# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(3)
print(x)

tensor([1.8137e-35, 0.0000e+00, 3.3631e-44])


In [4]:
x = torch.empty(2,3)
print(x)
x = torch.empty(3,2,3)
print(x)
x = torch.empty(1)
print(x)
x = torch.empty(4,2,3,5)
print(x)

tensor([[1.8137e-35, 0.0000e+00, 1.6816e-43],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])
tensor([[[1.8021e-35, 0.0000e+00, 7.0065e-44],
         [6.7262e-44, 6.3058e-44, 6.7262e-44]],

        [[7.9874e-44, 6.3058e-44, 6.8664e-44],
         [7.4269e-44, 1.1771e-43, 6.8664e-44]],

        [[7.0065e-44, 8.1275e-44, 7.1466e-44],
         [7.9874e-44, 8.1275e-44, 6.8664e-44]]])
tensor([1.8137e-35])
tensor([[[[1.4461e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.000

In [6]:
# torch.rand(size): produces a matrix of shape = size and random numbers in [0, 1] 
x = torch.rand([2,2])
print(x)

tensor([[0.2193, 0.0516],
        [0.9557, 0.3550]])


In [7]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1\
x = torch.zeros(2,2)
print(x)
x = torch.ones(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [8]:
#check size
print(x.size())
#check data type
print(x.dtype)

torch.Size([2, 2])
torch.float32


In [9]:
#float32 is a 32 bit number - float64 uses 64 bits. That means that float64's take up twice as much memory - 
#and doing operations on them may be a lot slower in some machine architectures. 
#However, float64's can represent numbers much more accurately than 32 bit floats. 
#They also allow much larger numbers to be stored.

In [13]:
# specify types, float32 default
x = torch.zeros(3,3 , dtype=torch.float16)
print(x)
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [15]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5,3],requires_grad=True)
print(x)
print(x.dtype)
print(x.size())

tensor([5.5000, 3.0000], requires_grad=True)
torch.float32
torch.Size([2])


In [16]:

# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y
print(z)
print(torch.add(x,y))

tensor([[1.4523, 1.1783],
        [0.5146, 1.7595]])
tensor([[1.4523, 1.1783],
        [0.5146, 1.7595]])


In [19]:
# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
print(y)
print(y.add_(x)) #this will modify y
print(y)

tensor([[1.4523, 1.1783],
        [0.5146, 1.7595]])
tensor([[2.0992, 1.8570],
        [0.8260, 2.6559]])
tensor([[2.0992, 1.8570],
        [0.8260, 2.6559]])


In [22]:
# substraction
z = x - y
print(z)
z = torch.sub(x, y)
print(z)

tensor([[-1.4523, -1.1783],
        [-0.5146, -1.7595]])
tensor([[-1.4523, -1.1783],
        [-0.5146, -1.7595]])


In [23]:
# multiplication
z = x * y  ##elementwise multiplication
print(z)
z = torch.mul(x,y) #elementwise multiplication
print(z)


tensor([[1.3581, 1.2604],
        [0.2572, 2.3809]])
tensor([[1.3581, 1.2604],
        [0.2572, 2.3809]])


In [24]:
# division
z = x / y
print(z)
z = torch.div(x,y)
print(z)

tensor([[0.3082, 0.3655],
        [0.3770, 0.3375]])
tensor([[0.3082, 0.3655],
        [0.3770, 0.3375]])


In [26]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.9753, 0.1030, 0.6485],
        [0.5231, 0.7702, 0.3907],
        [0.1367, 0.2159, 0.0690],
        [0.2480, 0.8557, 0.6118],
        [0.1488, 0.0049, 0.1751]])
tensor([0.9753, 0.5231, 0.1367, 0.2480, 0.1488])
tensor([0.5231, 0.7702, 0.3907])
tensor(0.7702)


In [31]:
# Get the actual value if only 1 element in your tensor
#only one element tensors can be converted to Python scalars
print(x[1,1].item())

0.7702391147613525


In [36]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
# the size -1 is inferred from other dimensions
# if -1 pytorch will automatically determine the necessary size
z = x.view(-1, 8)
w = x.view(1,-1,8)
print(x.size(), y.size(), z.size(),w.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([1, 2, 8])


In [50]:
# Numpy
import numpy as np
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)
print(type(a))

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [47]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print("a = {}".format(a))
print(type(a))
print("b = {}".format(b))
print(type(b))
# again be careful when modifying
a += 1
print(a)
print(b)

a = [1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
b = tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [63]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

In [64]:
if torch.cuda.is_available():
  print("Yes Gpu is available")